---

- name: Applying Common Tasks
  gather_facts: true
  hosts: minio
  roles:
    - common

- name: Installing nginx. Configure nginx reverse proxy and load balancer
  hosts: minio
  roles:
    - nginx

- name: Installing Minio
  gather_facts: true
  hosts: minio
  roles:
    - minio