---

- name: Downloading Minio
  become: true
  get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: "{{ minio_default_install_dir }}/minio"
    mode: 0775

- name: Creating minio Serivce
  become: true
  template:
    src: service.j2
    dest: /etc/systemd/system/minio.service

- name: copy EnvironmentFile
  become: true
  template:
    src: minio.j2
    dest: /etc/default/minio

- name: Starting minio Service
  become: true
  systemd:
    name: minio
    state: started
    enabled: true
    daemon_reload: true

